[group.misc]
user = "vos"
groups = ["power", "video"]

[package.misc]
name = [
  "man-db",
  "whois",
  "jq",
  "fzf",
  "exa",
  "curl",
  "wget",
  "make",
  "htop",
  "redis",
  "tree",
  "nnn",
  "playerctl",
  "laptop-detect",
  "unzip",
  "fd",
  "github-cli",
  "xorg-server",
  "xorg-xinit",
  "xorg-xsetroot",
  "alsa-utils",
  "xwallpaper",
  "wget",
  "mpv",
  "krita",
  "xclip",
  "flameshot",
  "dmenu",
  "redshift",
  "unclutter",
  "discord",
  "hsetroot",
  "imv",
  "weechat",
  "xdotool",
  "qemu",
  "libvirt",
  "gnome-boxes",
  "filelight",
  "firefox",
  "peek",
  "hugo",
  "peek",
  "xsel",
  "sed",
  "encfs",
  "pulseaudio-equalizer-ladspa",
]

[aur.misc]
name = [
  "xmousepasteblock-git",
  "proselint",
  "flyctl-bin",
  "heroku-cli-bin",
  "enpass-bin",
  "google-chrome",
  "spotify",
  "colorpicker",
  "slack-desktop",
]
