#! /bin/sh

if laptop-detect; then
  xrdb -merge "$HOME/.Xresources.laptop"
fi

sxhkd &
picom &
redshift -l $(curl -s "https://location.services.mozilla.com/v1/geolocate?key=geoclue" | jq -r '"\(.location.lat):\(.location.lng)"') &
xmousepasteblock &
hsetroot -solid '#F7FAFC' &
xsetroot -cursor_name left_ptr &
unclutter --timeout 1 &
random-quote-wallpaper &

if [[ $(hostnamectl hostname) = "desktop" ]]; then
  # stop autofocusing the camera
  v4l2-ctl \
    --media-bus-info usb-0000:00:14.0-2 \
    --device "HD Pro Webcam C920" \
    --set-ctrl focus_auto=0 &

  # delay shutting down the monitor
  xset s 3600 3600 &
  xset -dpms &
fi

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        5
bspc config window_gap          10

bspc config automatic_scheme     alternate
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       false

bspc config normal_border_color '#1E2127'
bspc config focused_border_color '#61afef'

bspc config pointer_modifier mod1
bspc config pointer_action1 resize_side
bspc config pointer_action1 resize_corner
bspc config pointer_action3 move

# bspc rule --add Google-chrome desktop='^2'
bspc rule --add discord desktop='^3'
bspc rule --add Slack desktop='^4'
bspc rule --add spotify desktop='^5'
bspc rule --add Peek state=floating

bspc rule --add Enpass --one-shot desktop='^9' focus=off
enpass &
