#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

function apt-installed() {
    PACKAGE=$1
    dpkg-query -W -f='${Status}' "$PACKAGE" 2>/dev/null | grep "ok installed" --silent
}

function snap-installed() {
    PACKAGE=$1
    snap info "$PACKAGE" 2>/dev/null | grep "installed:" --silent
}

function apt-install() {
    PACKAGE="$1"
    if ! apt-installed "$PACKAGE"; then
        sudo apt install "$PACKAGE"
    fi
}

function apt-install-deb() {
    PACKAGE="$1"
    URL="$2"

    if ! apt-installed "$PACKAGE"; then
        FILE_PATH="$PACKAGE.deb"

        wget -O "$FILE_PATH" "$URL"
        sudo dpkg -i "$FILE_PATH"
        rm "$FILE_PATH"
    fi
}

function snap-install() {
    PACKAGE="$1"
    if ! snap-installed "$PACKAGE"; then
        sudo snap install "$PACKAGE"
    fi
}

function snap-install-classic() {
    PACKAGE="$1"
    if ! snap-installed "$PACKAGE"; then
        sudo snap install "$PACKAGE" --classic
    fi
}

function apt-uninstall() {
    PACKAGE="$1"
    if apt-installed "$PACKAGE"; then
        sudo apt remove "$PACKAGE"
    fi
}

function add-line-to-file() {
    FILE="$1"
    LINE="$2"

    grep -qxF "$LINE" "$FILE" || echo "$LINE" >>"$FILE"
}

apt-install git
apt-install curl
apt-install snapd
apt-uninstall io.elementary.code
snap-install-classic code
apt-install fonts-liberation
apt-install-deb "google-chrome-stable" "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
snap-install discord
snap-install enpass

apt-install stow
stow git
stow asdf

if [ ! -d "$HOME/.asdf" ]; then
    git clone "https://github.com/asdf-vm/asdf.git" "$HOME/.asdf" --branch v0.11.3
fi
add-line-to-file "$HOME/.bashrc" '. "$HOME/.asdf/asdf.sh"'
add-line-to-file "$HOME/.bashrc" '. "$HOME/.asdf/completions/asdf.bash"'
. "$HOME/.asdf/asdf.sh"
. "$HOME/.asdf/completions/asdf.bash"
asdf plugin list | grep --quiet nodejs || asdf plugin add nodejs
NODEJS_VERSION="19.8.1"
asdf list nodejs | grep --quiet "$NODEJS_VERSION" || asdf install nodejs "$NODEJS_VERSION"

add-line-to-file "$HOME/.bashrc" 'export PATH="$HOME/.dotfiles/scripts:$PATH"'
PATH="$HOME/.dotfiles/scripts:$PATH"
