#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

sudo pacman -S --needed --noconfirm \
  github-cli \
  xorg-server \
  xorg-xinit \
  xorg-xsetroot \
  alsa-utils \
  xwallpaper \
  ttf-ubuntu-font-family \
  ttf-dejavu \
  ttf-liberation \
  noto-fonts \
  wget \
  mpv \
  krita \
  xclip \
  flameshot \
  ttf-hack \
  bspwm \
  sxhkd \
  dmenu \
  rofi \
  dunst \
  redshift \
  unclutter \
  discord \
  picom \
  alacritty \
  hsetroot \
  imv \
  weechat \
  xdotool

function yay-install() {
  for package in $@; do
    if ! pacman -Qi "$package"; then
      yay -S --needed --noconfirm "$package"
    fi
  done
}

yay-install \
  heroku-cli \
  hugo \
  asdf-vm \
  ly \
  yaru-gtk-theme \
  enpass-bin \
  google-chrome \
  firefox \
  slack-desktop \
  pick-colour-picker \
  tex-gyre-fonts \
  otf-libertinus \
  noto-fonts-emoji \
  peek \
  postgresql \
  postgresql-libs \
  xmousepasteblock-git \
  font-manager

./installers/postgres.sh
./installers/fonts.sh
./installers/ly.sh
./installers/spotify.sh
