#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

sudo pacman -S --needed --noconfirm \
  github-cli \
  xorg-server \
  xorg-xinit \
  xorg-xsetroot \
  alsa-utils \
  xwallpaper \
  ttf-ubuntu-font-family \
  wget \
  mpv \
  krita \
  xclip \
  flameshot \
  gnome-tweak-tool \
  ttf-hack \
  bspwm \
  sxhkd \
  dmenu \
  rofi \
  dunst \
  redshift \
  unclutter \
  discord \
  picom \
  alacritty \
  hsetroot \
  imv

yay -S --needed --noconfirm \
  heroku-cli \
  hugo \
  asdf-vm \
  ly \
  yaru-gtk-theme \
  enpass-bin \
  google-chrome \
  slack-desktop \
  rofi-greenclip \
  pick-colour-picker \
  typora \
  tex-gyre-fonts \
  otf-libertinus \
  noto-fonts-emoji \
  peek

./installers/postgres.sh
./installers/fonts.sh
./installers/ly.sh
./installers/spotify.sh
