#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

PREVIOUS_PWD="$(pwd)"
if ! command -v "yay" &> /dev/null; then
  echo "Installing yay..."
  cd "$(mktemp -d)"
  git clone https://aur.archlinux.org/yay.git
  cd yay
  makepkg -si --noconfirm
  cd "$PREVIOUS_PWD"
fi

function yay-install() {
  for package in "$@"; do
    if ! pacman -Qi "$package" > /dev/null; then
      yay -S --needed --noconfirm "$package"
    fi
  done
}

function pacman-install() {
  sudo pacman -S --needed --noconfirm "$@"
}

pacman-install $(cat packages.txt)
yay-install $(cat aur-packages.txt)

stow --verbose --dir "$HOME/.dotfiles/configs" --target ~ $(ls "$HOME/.dotfiles/configs")

./installers/groups.sh
./installers/services.sh

./installers/fish.sh
./installers/nordvpn.sh
./installers/kakoune.sh
./installers/postgres.sh
./installers/fonts.sh

echo "Done!"
