#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

source ./helpers.sh

if [[ $OSTYPE == 'darwin'* ]]; then
    ./install-osx-packages.sh
elif lsb_release --description | grep "elementary OS" --silent; then
    ./install-elementary-packages.sh
fi

stow git
stow asdf

./install-asdf.sh
./install-scripts.sh
