#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

sudo mkdir -p /etc/systemd/system/getty@tty1.service.d

FILE_PATH="/etc/systemd/system/getty@tty1.service.d/autologin.conf"
if [[ ! -f "$FILE_PATH" ]]; then
  echo "[Service]" | sudo tee "$FILE_PATH"
  echo "ExecStart=" | sudo tee -a "$FILE_PATH"
  echo "ExecStart=-/sbin/agetty -o '-p -f -- \\u' --noclear --autologin $USER - \$TERM" | sudo tee -a "$FILE_PATH"
fi
