#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

if [[ ! -d /boot/EFI/Microsoft ]]; then
  sudo mount /dev/sdb2 /mnt
  sudo cp -r /mnt/EFI/Microsoft/ /boot/EFI/Microsoft
  sudo umount /mnt
  sudo bootctl update
fi
