#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

sudo pacman -S --needed --noconfirm \
  man-db \
  whois \
  jq \
  fzy \
  git \
  stow \
  exa \
  openssh \
  gvim \
  curl \
  wget \
  make \
  htop \
  shellcheck \
  ctags \
  redis \
  tig \
  tree \
  nnn \
  playerctl \
  laptop-detect \
  unzip \
  kakoune \
  ripgrep \
  fish

function yay-install() {
  for package in $@; do
    if ! pacman -Qi "$package"; then
      yay -S --needed --noconfirm "$package"
    fi
  done
}

yay-install \
  nordvpn-bin \
  tldr-sh

./installers/dotfiles.sh
./installers/fish.sh
./installers/nordvpn.sh
./installers/ssh.sh
./installers/vim.sh
./installers/kakoune.sh
