"$schema" = 'https://starship.rs/config-schema.json'

[aws]
disabled = true

[bun]
format = 'via [$symbol]($style) '

[golang]
format = 'via [$symbol]($style) '

[nodejs]
disabled = true

[package]
disabled = true

[python]
format = 'via [$symbol]($style) '

[ruby]
disabled = true
