#! /bin/sh

setxkbmap -option ctrl:nocaps
hsetroot -solid "#1b202a"

dunst &
unclutter &
redshift &
notify-on-low-battery &
sxhkd &
vbar &
xprop -root -spy _NET_ACTIVE_WINDOW | while read -r LINE; do vbar --update title; done &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
