#! /bin/sh

setxkbmap -option ctrl:nocaps
xsetroot -cursor_name left_ptr

THEME="light"
if [ "$THEME" = "light" ]; then
	BACKGROUND="#e4dfd5"
else
	BACKGROUND="#1b202a"
fi
hsetroot -solid "$BACKGROUND"
feh --bg-max ~/.dotfiles/wallpapers/nnLP9U6.png

compton &
dunst &
unclutter &
redshift &
notify-on-low-battery &
sxhkd &
vbar start > /home/andrewvos/vbar.log 2>&1 &
xprop -root -spy _NET_CURRENT_DESKTOP | while read -r LINE; do vbar update --name desktops; done &
highlight-active-window &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
