tasks:
# https://gist.github.com/YoEight/d19112db56cd8f93835bf2d009d617f7

- pacman:
    name:
      - font-manager
      - ttf-ubuntu-font-family
      - ttf-dejavu
      - ttf-liberation
      - noto-fonts
      - noto-fonts-emoji
      - tex-gyre-fonts
      - libertinus-font
      - terminus-font
      - ttf-hack

- aur:
    name:
      - ttf-sudo
      - otf-helvetica-neue

- symlink:
    sudo: true
    from: "/etc/fonts/local.conf"
    to: "local.conf"

- symlink:
    sudo: true
    from: "/etc/fonts/conf.d/70-no-bitmaps.conf"
    to: "/usr/share/fontconfig/conf.avail/70-no-bitmaps.conf"

- symlink:
    sudo: true
    from: "/etc/fonts/conf.d/10-sub-pixel-rgb.conf"
    to: "/usr/share/fontconfig/conf.avail/10-sub-pixel-rgb.conf"

- symlink:
    sudo: true
    from: "/etc/fonts/conf.d/11-lcdfilter-default.conf"
    to: "/usr/share/fontconfig/conf.avail/11-lcdfilter-default.conf"

- script:
    command: |
      INCLUDE_LINE='export FREETYPE_PROPERTIES="truetype:interpreter-version=40"'
      FILE_PATH="/etc/profile.d/freetype2.sh"
      grep -qxF "$INCLUDE_LINE" $FILE_PATH || echo "$INCLUDE_LINE" | sudo tee -a "$FILE_PATH"
