- pacman:
    name:
      - yaru-gtk-theme

- aur:
    name:
      - nordic-theme

- symlink:
    from: "~/.gtkrc-2.0"
    to: ".gtkrc-2.0"

- symlink:
    from: "~/.config/gtk-3.0"
    to: "gtk-3.0"
