#! /bin/sh

if laptop-detect; then
  xrdb -merge $HOME/.Xresources.laptop
fi

sxhkd &
picom &
redshift &
xmousepasteblock &
hsetroot -solid '#F7FAFC' &
xsetroot -cursor_name left_ptr &
unclutter --timeout 1 &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        5
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc config normal_border_color '#1E2127'
bspc config focused_border_color '#61afef'

bspc rule --add Google-chrome desktop='^2'
bspc rule --add discord desktop='^3'
bspc rule --add Slack desktop='^4'
bspc rule --add spotify desktop='^5'
bspc rule --add Peek state=floating

bspc rule --add Enpass --one-shot desktop='^10' focus=off
enpass &
