#! /bin/sh

if laptop-detect; then
  xrdb -merge $HOME/.Xresources
fi
sxhkd &
compton &

feh --bg-center $HOME/.wallpapers/Uss9jsw.jpg

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Google-chrome desktop='^2'
bspc rule -a discord desktop='^3'
bspc rule -a Slack desktop='^4'
bspc rule -a spotify desktop='^5'
