source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/plug.kak" noload

plug DERPSQUID9/kakoune-cyberpunk-neon theme
plug yasukotelin/shirotelin theme
plug evanrelf/primer.kak theme
plug nesyamun/nord-kakoune theme
plug Icantjuddle/ayu-kak theme
plug caksoylar/kakoune-snow theme

colorscheme nord-light

plug h-youhei/kakoune-surround

set global grepcmd 'rg --column'

# Disable clippy
set-option global ui_options ncurses_assistant=off

# keep space around cursor
set-option global scrolloff 10,10

# save on pressing enter
hook global NormalKey <ret> w

# search with c tags
map global goto s -docstring 'search ctags' %{<esc><a-i>w: ctags-search<ret>}

add-highlighter global/ number-lines
add-highlighter global/ show-matching

hook global InsertChar \t %{ exec -draft -itersel h@ }
set global tabstop 2
set global indentwidth 2

hook global KakBegin .* %{
  evaluate-commands %sh{
    if [ -e "$PWD/.git/tags" ]; then
      printf "%s\n" "set-option -add current ctagsfiles %{$PWD/.git/tags}"
    fi
  }
}

map global goto n '<esc>: grep-next-match<ret>' -docstring 'next grep match'
map global goto p '<esc>: grep-previous-match<ret>' -docstring 'previous grep match'

# Lint
hook global WinSetOption filetype=sh %{
  set-option window lintcmd "shellcheck -fgcc -Cnever"
}
hook global WinSetOption filetype=(markdown|plain) %{
  set-option window lintcmd "proselint"
}

hook global WinSetOption filetype=ruby %{
  set-option window lintcmd 'rubocop -l --format emacs'
}

# Automatic linting
hook global WinSetOption filetype=(sh|markdown|plain) %{
  hook buffer BufWritePost "\Q%val{buffile}" lint
}

# Format
# yarn global add prettier @prettier/plugin-ruby
hook global BufSetOption filetype=(javascript|ruby|css|scss|json) %{
  set-option buffer formatcmd "prettier --stdin-filepath=%val{buffile}"
}

def rspec \
  -override \
  -docstring "Run an rspec spec" \
  -params 1 \
  -shell-script-candidates %{ find spec/**/*_spec.rb } \
  %{
    terminal  sh -c "bundle exec rspec %arg{@} ;  read -n 1 -s -r -p 'Press any key to continue'"
  }
