source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/plug.kak" noload

plug DERPSQUID9/kakoune-cyberpunk-neon theme
plug yasukotelin/shirotelin theme
plug evanrelf/primer.kak theme
plug nesyamun/nord-kakoune theme
plug Icantjuddle/ayu-kak theme
plug caksoylar/kakoune-snow theme

colorscheme reeder

plug h-youhei/kakoune-surround

set global grepcmd 'rg --column'

# Disable clippy
set-option global ui_options ncurses_assistant=off

# keep space around cursor
set-option global scrolloff 10,10

# user mappings
map -docstring "yank the selection into the clipboard" global user y "<a-|> xsel --input --clipboard<ret>"
map -docstring "paste the clipboard" global user p "<a-!> xsel<ret>"
map -docstring "surround" global user s ": surround<ret>"

# save on pressing enter
hook global NormalKey <ret> %{
  evaluate-commands %sh{
    if [ -n "${kak_opt_formatcmd}" ]; then
      printf "%s\n" "format"
    fi
    printf "%s\n" "write"
  }
}

# search with c tags
map global goto s -docstring 'search ctags' %{<esc><a-i>w: ctags-search<ret>}

# map # to comment-line
map global normal "#" ": comment-line<ret>"

add-highlighter global/ number-lines
add-highlighter global/ show-matching
add-highlighter global/ number-lines -relative -hlcursor

add-highlighter global/show-trailing-whitespaces regex '\h+$' 0:Error

hook global InsertChar \t %{ exec -draft -itersel h@ }
set global tabstop 2
set global indentwidth 2

hook global KakBegin .* %{
  evaluate-commands %sh{
    if [ -e "$PWD/.git/tags" ]; then
      printf "%s\n" "set-option -add current ctagsfiles %{$PWD/.git/tags}"
    fi
  }
}

map global goto n '<esc>: grep-next-match<ret>' -docstring 'next grep match'
map global goto p '<esc>: grep-previous-match<ret>' -docstring 'previous grep match'

# Lint
hook global WinSetOption filetype=sh %{
  set-option window lintcmd "shellcheck -fgcc -Cnever"
}
hook global WinSetOption filetype=(markdown|plain) %{
  set-option window lintcmd "proselint"
}

hook global WinSetOption filetype=ruby %{
  set-option window lintcmd 'rubocop -l --format emacs'
}

hook global WinSetOption filetype=(html|erb) %{
  set-option buffer formatcmd "run(){ tidy -q --indent yes --indent-spaces %opt{tabstop}  2>/dev/null || true; } && run"
}

# Automatic linting
hook global WinSetOption filetype=(sh|markdown|plain) %{
  hook buffer BufWritePost "\Q%val{buffile}" lint
}

# Format
# yarn global add prettier @prettier/plugin-ruby
hook global BufSetOption filetype=(javascript|ruby|css|scss|json) %{
  set-option buffer formatcmd "prettier --stdin-filepath=%val{buffile}"
}

def rspec \
  -override \
  -docstring "Run an rspec spec" \
  -params 1 \
  -file-completion \
  %{
    terminal sh -c "bundle exec rspec %arg{@} ;  read -n 1 -s -r -p 'Press any key to continue'"
  }

declare-option str rspec_current_spec ""
def run-current-spec \
  -override \
  -docstring "Run the current spec" \
  -params 0 \
  %{
    evaluate-commands %sh{
      current_spec="$kak_opt_rspec_current_spec"
      current_file="$kak_buffile"

      if [[ "$current_file" == *_spec.rb ]]; then
        current_spec="$current_file"
        printf "%s\n" "set-option global rspec_current_spec $current_file"
      fi

      if [ -n "$current_spec" ]; then
        printf "%s\n" "terminal sh -c \"bundle exec rspec $current_spec ;  read -n 1 -s -r -p 'Press any key to continue'\""
      fi
    }
  }

map global normal <c-t> ': run-current-spec<ret>'

def git-open \
  -override \
  -docstring "Open git changed files" \
  -params 1 \
  -shell-script-completion %{git status --untracked --porcelain | grep -v '^ D ' | awk '{print ( $(NF) )}'} \
  %{
    edit %arg{@}
  }
alias global g git-open


# github
declare-user-mode git
map -docstring 'create gist from buffer' global git g '<a-|>gh gist create --web "$kak_buffile"<ret>'
map -docstring 'create gist from selection' global git s '<a-|>gh gist create --web --filename $(basename "$kak_buffile")<ret>'
map -docstring 'view repo' global git v '<a-|>gh repo view --web<ret>'
map -docstring 'git' global user g ':enter-user-mode git<ret>'
