#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

if [ "$#" -eq 0 ]; then
  echo "Again runs your commands again and again"
  echo
  echo "Usage:"
    echo "  again [command] [arguments...]"
  exit 1
fi

function wait-for-key() {
  read -s -n 1 key
  if [[ ! $key = "" ]]; then
    wait-for-key
  fi
}

while true; do
  "$@" ||:

  echo "Press <Enter> to go again or [CTRL-c] to quit..."
  wait-for-key
done
