#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

all_desktops=$(bspc query --desktops --names)
active_desktop=$(bspc query --desktops --names -d .focused)

for desktop in $all_desktops; do
  if [[ "$desktop" = "$active_desktop" ]]; then
    echo -n ""
    exit 0
  else
    echo -n ""
  fi
done
