#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# Delete any branches that have been merged.
# git branch --merged master | grep -v -e 'master' -e '\*' | xargs -n 1 git branch -d
set +e
LOCAL_BRANCHES=$(git branch --merged master | grep -v -e 'master' -e '\*' | tr -d ' ')
set -e

if [[ -n "$LOCAL_BRANCHES" ]]; then
  for BRANCH in $LOCAL_BRANCHES; do
    git branch -d "$BRANCH"
  done
fi

# Prune any stale references
git remote prune origin
