#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

set +u
MAIN_BRANCH="$1"
set -u
if [[ "$MAIN_BRANCH" = "" ]]; then
  MAIN_BRANCH="main"
fi

set +e
LOCAL_BRANCHES=$(git branch --merged $MAIN_BRANCH | grep -v -e $MAIN_BRANCH -e '\*' | tr -d ' ')
set -e

if [[ -n "$LOCAL_BRANCHES" ]]; then
  for BRANCH in $LOCAL_BRANCHES; do
    git branch -d "$BRANCH"
  done
fi

# Prune any stale references
git remote prune origin
