#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

function write-title() {
  echo "• $1"
}

function write-command() {
  echo "  > $1"
  echo
}

write-title 'Flushing DNS'
write-command 'sudo systemd-resolve --flush-caches'

write-title 'Unstaging a file in git'
write-command 'git reset HEAD <file>'
