#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

echo '  Help'

function write-title() {
  echo
  echo "• $1"
}

function write-command() {
  echo "  > $1"
}

write-title 'Flush DNS'
write-command 'sudo systemd-resolve --flush-caches'

write-title 'Unstage a file in git'
write-command 'git reset HEAD <file>'

write-title 'Undo some unstaged changes in git'
write-command 'git checkout -p'

write-title 'Jump between methods in vim'
write-command '[m ]m, [M ]M'

write-title 'Select inside method body'
write-command 'vim'

write-title 'Select around method body'
write-command 'vam'

write-title 'Run a local script on heroku'
write-command 'cat script.rb | heroku run console --app APP_NAME --no-tty'

write-title 'Add a user to a group'
write-command 'usermod -a -G GROUP_NAME USER'

write-title 'SSH keys permissions'
write-command 'chmod 600 ~/.ssh/id_rsa'
write-command 'chmod 644 ~/.ssh/id_rsa.pub'

write-title 'Rails migrations'
write-command 'rails generate migration AddPartNumberToProducts part_number:string:index'

write-title 'Rails transactions'
write-command 'ActiveRecord::Base.transaction do; end'

write-title 'Flush cache in chrome'
write-command 'chrome://net-internals/#dns'

write-title 'Flush cache in arch'
write-command 'sudo systemd-resolve --flush-caches'

write-title 'Upgrade all packages in yarn'
write-command 'yarn upgrade-interactive --latest'

write-title 'List installed packages'
write-command 'pacman -Qqe'
