#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

function write-title() {
  echo "• $1"
}

function write-command() {
  echo "  > $1"
  echo
}

write-title 'Flush DNS'
write-command 'sudo systemd-resolve --flush-caches'

write-title 'Unstage a file in git'
write-command 'git reset HEAD <file>'

write-title 'Jump between methods in vim'
write-command '[m ]m, [M ]M'

write-title 'Select inside method body'
write-command 'vim'

write-title 'Select around method body'
write-command 'vam'
