#!/usr/bin/env bash

tag_index="$1"
current_tag_index="$(herbstclient get_attr tags.focus.index)"

if [[ "$tag_index" = "$current_tag_index" ]]; then
  herbstclient use_previous
else
  herbstclient use_index "$tag_index"
fi
