#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

HEROKU_HASH=$(heroku releases | grep Deploy |head -n1 |cut -d ' ' -f4)
LOCAL_HASH=$(git rev-parse HEAD)

if [[ $LOCAL_HASH = $HEROKU_HASH* ]]; then
  echo 'Up to date'
else
  echo 'Not yet deployed'
fi
