#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

echo "Waiting for Heroku release hash to equal HEAD..."
echo "Press [CTRL+C] to stop.."

while :
do
  HEROKU_HASH=$(heroku releases | grep Deploy |head -n1 |cut -d ' ' -f4)
  LOCAL_HASH=$(git rev-parse --short=8 HEAD)

  echo -n "LOCAL: $LOCAL_HASH"
  echo -n -e '\t'
  echo -n "REMOTE: $HEROKU_HASH"
  echo

  if [[ $LOCAL_HASH = $HEROKU_HASH ]]; then
    notify-send "Heroku is up to date"
    break
  fi

	sleep 5
done
