#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

function volume () {
  amixer get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1
}

function is_mute {
  amixer get Master | grep '%' | grep -oE '[^ ]+$' | grep off > /dev/null
}

volume=$(volume)
if is_mute; then volume=0; fi

bar=$(seq -s "─" $(($volume / 5)) | sed 's/[0-9]//g')

dunstify --replace 2593 -u normal "$bar"
