#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

MAIN_BRANCH=$(git remote show origin | sed -n '/HEAD branch/s/.*: //p')
CURRENT_BRANCH=$(git branch --show-current)

if [[ "$CURRENT_BRANCH" = "$MAIN_BRANCH" ]]; then
  echo "You probably don't want to pull request from \"$CURRENT_BRANCH\"?"
  exit 1
fi

git push --set-upstream origin "$CURRENT_BRANCH"
gh pr create --base "$MAIN_BRANCH" --fill --web
