#!/bin/bash
set -euo pipefail
IFS=$'\n\t'


set -x


notify-send "Select a window/area to record..."
AREA=$(slop)

OUTPUT=$(mktemp --dry-run --suffix ".gif")
notify-send "Recording started, press ALT-s to save or Escape to cancel..."
menyoki record  --root --countdown 0 --size "$AREA" gif --fast save "$OUTPUT"

if [[ -s "$OUTPUT" ]]; then
  notify-send "Recording saved to $OUTPUT..."
else
  notify-send "Recording cancelled..."
fi
