#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# `xprop WM_CLASS` to get WINDOW_CLASS
WORKSPACE="$1"
WINDOW_CLASS="$2"
COMMAND="$3"

i3-msg workspace "$WORKSPACE"
RESULT=$(i3-msg "[class=$WINDOW_CLASS] focus")
[ "$RESULT" = '[{"success":true}]' ] || i3-msg "exec --no-startup-id '$COMMAND'"
