#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# dependencies: ffcast imagemagick

set -x

export RUNNING="/tmp/recording.screencast"

if [[ -f "$RUNNING" ]]; then
  pkill -f ffmpeg
  exit 0
else
  touch "$RUNNING"
  trap 'rm $RUNNING' EXIT
fi


mkdir -p "$HOME/Screencasts"

TMP_AVI=$(mktemp /tmp/outXXXXXXXXXX.avi)
GIF=$HOME/Screencasts/$(date +%Y-%m-%d-%H-%M-%S.gif)

ffcast -s % ffmpeg -y -f x11grab -show_region 1 -framerate 15 \
  -video_size %s -i %D+%c -codec:v huffyuv                  \
  -vf crop="iw-mod(iw\\,2):ih-mod(ih\\,2)" "$TMP_AVI" || :

convert -set delay 10 -layers Optimize "$TMP_AVI" "$GIF"

notify-send "Saved gif $GIF"
