#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

NOTES_PATH="$HOME/.notes"

git -C "$NOTES_PATH" add .

if git -C "$NOTES_PATH" commit -m "$(date '+%d-%m-%Y %H:%M:%S')"; then
  git -C "$NOTES_PATH" pull --rebase
  git -C "$NOTES_PATH" push
else
  git -C "$NOTES_PATH" pull --rebase
fi

notify-send 'Sync complete'
