#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

function backup() {
  BOX=$(uname -n)
  DATE=$(date +%Y-%m-%d_%H-%M-%S)
  DIRECTORY=$1
  DIRECTORY_LOWERCASE=$(echo $DIRECTORY | tr "[:upper:]" "[:lower:]")
  BACKUP_NAME="$BOX-$DATE-$DIRECTORY_LOWERCASE"

  echo $BACKUP_NAME

  /usr/local/bin/tarsnap -c \
    -v \
    --humanize-numbers \
    --keyfile /home/andrewvos/.tarsnap.write.key \
    -f  "$BACKUP_NAME" \
    $DIRECTORY
}

cd $HOME

backup Documents
backup Pictures
backup backups
