#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

focused_desktop=""
occupied_desktop=""

for tag in $(herbstclient tag_status); do
  type="${tag//[0-9]/}"
  number="${tag//[!0-9]/}"

  if [[ "$type" = "#" ]]; then
    focused_desktop="$number"
  elif [[ "$type" = ":" ]]; then
    occupied_desktop="$number"
  fi
done

last_desktop="$focused_desktop"
if [[ "$occupied_desktop" != "" ]]; then
  if [[ "$occupied_desktop" -gt "$last_desktop" ]]; then
    last_desktop="$occupied_desktop"
  fi
fi

for desktop in $(seq 1 9); do
  if [[ "$desktop" = "$focused_desktop" ]]; then
    echo -n ""
  else
    echo -n ""
  fi

  if [[ "$desktop" = "$last_desktop" ]]; then
    exit 0
  fi
done
