#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

if [[ "$1" == "up" ]]; then
  amixer -q sset Master 5%+ unmute
elif [[ "$1" == "down" ]]; then
  amixer -q sset Master 5%- unmute
elif [[ "$1" == "toggle" ]]; then
  amixer -q sset Master toggle
fi
