#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

function volume () {
  amixer get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1
}

function is_mute () {
  amixer get Master | grep '%' | grep -oE '[^ ]+$' | grep off > /dev/null
}

function volume_icon () {
  volume=$(volume)
  if is_mute; then
    echo ""
  elif [[ "$volume" = "0" ]]; then
    echo ""
  elif [[ volume -lt 50 ]]; then
    echo ""
  else
    echo ""
  fi
}

function volume_percentage () {
  volume=$(volume)
  if is_mute; then
    echo "M"
  else
    echo "$volume%"
  fi
}

if [[ "$1" == "icon" ]]; then
  volume_icon
elif [[ "$1" == "percentage" ]]; then
  volume_percentage
elif [[ "$1" == "up" ]]; then
  amixer -q sset Master 5%+ unmute
  vbar update --name volume
  vbar update --name volume-icon
elif [[ "$1" == "down" ]]; then
  amixer -q sset Master 5%- unmute
  vbar update --name volume
  vbar update --name volume-icon
elif [[ "$1" == "toggle" ]]; then
  amixer -q sset Master toggle
  vbar update --name volume
  vbar update --name volume-icon
fi
