#!/bin/bash

# Call with a percentage value from 0 to 100
# 0 means only red and green, 50 means half of blue is shown through
# if you don't give any arguments the calibration is cleared

if [[ -z "$1" ]]; then
  echo Clearing all calibrations
  xcalib -clear
else
  FILTER=$1
  if [ "$FILTER" == "night" ]; then
    FILTER=30
  elif [ "$FILTER" == "day" ]; then
    FILTER=90
  fi
  echo Setting FILTER to $FILTER
  xcalib -clear && xcalib -green 1 1 $((100 - ( 100 - $FILTER ) / 2 )) -blue 1 1 $FILTER -alter
fi
