#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

bspc desktop --focus "$1"

if [[ "$1" = "^2" ]]; then
  ps -C chrome || google-chrome-stable
elif [[ "$1" = "^3" ]]; then
  ps -C Discord || discord
elif [[ "$1" = "^4" ]]; then
  ps -C slack || slack
elif [[ "$1" = "^5" ]]; then
  ps -C spotify || spotify
fi
