#!/bin/bash

set -e

BASE_FONT="mplus"

BORDER="2px"
BACKGROUND="#f7f3ee"
ICON_BACKGROUND="#dde4f2"
TEXT_BACKGROUND="#f1ddf1"
TEXT_FOREGROUND="#605a52"

vbar add-css --class bar --css "font-family: $BASE_FONT;"
vbar add-css --class bar --css "font-weight: normal;"
vbar add-css --class bar --css "font-size: 14px;"
vbar add-css --class bar --css "text-shadow: none;"
vbar add-css --class bar --css "background-color: $BACKGROUND;"
vbar add-css --class bar --css "border: $BORDER solid $BACKGROUND;"

vbar add-css --class block --css "padding-top: 2px;"
vbar add-css --class block --css "padding-bottom: 2px;"
vbar add-css --class block --css "padding-left: 6px;"
vbar add-css --class block --css "padding-right: 6px;"
vbar add-css --class block --css "color: $TEXT_FOREGROUND;"
vbar add-css --class block --css "background-color: $TEXT_BACKGROUND;"

vbar add-css --class menu --css "font-family: $BASE_FONT;"
vbar add-css --class menu --css "font-weight: normal;"
vbar add-css --class menu --css "font-size: 14px;"
vbar add-css --class menu --css "text-shadow: none;"
vbar add-css --class menu --css "background-color: $TEXT_BACKGROUND;"
vbar add-css --class menu --css "color: $TEXT_FOREGROUND;"
vbar add-css --class menu --css "border: 2px solid $TEXT_BACKGROUND;"

vbar add-css --class "menu :hover" --css "background-color: $ICON_BACKGROUND;"
vbar add-css --class "menu :hover" --css "color: $TEXT_FOREGROUND;"

vbar add-css --class power-off-icon --css "font-family: \"Font Awesome\";"
vbar add-css --class power-off-icon --css "font-size: 14px;"
vbar add-css --class power-off-icon --css "background-color: $ICON_BACKGROUND;"

vbar add-css --class title --css "background-color: $BACKGROUND;"

vbar add-css --class battery-icon --css "font-family: \"Font Awesome\";"
vbar add-css --class battery-icon --css "font-size: 14px;"
vbar add-css --class battery-icon --css "background-color: $ICON_BACKGROUND;"

vbar add-css --class screenshot --css "font-family: \"Font Awesome\";"
vbar add-css --class screenshot --css "font-size: 14px;"
vbar add-css --class screenshot --css "background-color: $ICON_BACKGROUND;"
vbar add-css --class screenshot --css "margin-right: 2px;"

vbar add-css --class volume-icon --css "font-family: \"Font Awesome\";"
vbar add-css --class volume-icon --css "font-size: 14px;"
vbar add-css --class volume-icon --css "background-color: $ICON_BACKGROUND;"

vbar add-css --class volume --css "margin-right: 2px;"

vbar add-css --class wireless-icon --css "font-family: \"Font Awesome\";"
vbar add-css --class wireless-icon --css "font-size: 14px;"
vbar add-css --class wireless-icon --css "background-color: $ICON_BACKGROUND;"

vbar add-css --class wireless --css "margin-right: 2px;"

vbar add-css --class date-icon --css "font-family: \"Font Awesome\";"
vbar add-css --class date-icon --css "font-size: 14px;"
vbar add-css --class date-icon --css "background-color: $ICON_BACKGROUND;"
vbar add-css --class date --css "margin-right: 2px;"

vbar add-css --class time-icon --css "font-family: \"Font Awesome\";"
vbar add-css --class time-icon --css "font-size: 14px;"
vbar add-css --class time-icon --css "background-color: $ICON_BACKGROUND;"
vbar add-css --class time --css "margin-right: 2px;"

vbar add-block --left --name power-off-icon --text ""
vbar add-menu --name power-off-icon --text "Log off" --command "i3-msg exit"
vbar add-menu --name power-off-icon --text "Restart" --command "reboot"
vbar add-menu --name power-off-icon --text "Shut down" --command "poweroff"

vbar add-block --center --name title --tail-command "xtitle -s"

vbar add-block --right --name screenshot  --text "" --click-command "flameshot gui"

vbar add-block --right --name volume-icon --command "volume icon" --click-command "volume toggle"

vbar add-block --right --name volume --command "volume percentage" --click-command "volume toggle"

if [[ -d "/sys/class/power_supply/BAT0" ]]; then
  vbar add-block --right --name battery-icon --text ''
  vbar add-css --class "battery-0" --css "margin-right: 0;"
fi

for battery_number in {0..9}; do
  if [[ -d "/sys/class/power_supply/BAT$battery_number" ]]; then
    vbar add-css --class "battery-$battery_number" --css "margin-right: 2px;"

    vbar add-block --right --name battery --command "battery-percent $battery_number" --interval 5
  fi
done

if [[ -d "/sys/class/power_supply/BAT0" ]]; then
  vbar add-block --right --name wireless-icon --text ""
  vbar add-block --right --name wireless --command "netctl-auto list | grep '* ' | sed 's/* //'" --interval 5
fi

vbar add-block --right --name date-icon --text ""
vbar add-block --right --name date --command "date +%d/%m" --interval 60
vbar add-block --right --name time-icon --text ""
vbar add-block --right --name time --command "date +%H:%M" --interval 1
