#!/bin/bash

set -e

THEME="light"
BASE_FONT="mplus"

if [[ "$THEME" = "light" ]]; then
	BORDER="10px"
	BACKGROUND="#e4dfd5"
	ICON_BACKGROUND="#dcd6c9"
	TEXT_BACKGROUND="#cdc3b2"
	TEXT_FOREGROUND="#655842"
elif [[ "$THEME" = "dark" ]]; then
	BORDER="10px"
	BACKGROUND="#1b202a"
	ICON_BACKGROUND="#232936"
	TEXT_BACKGROUND="#323c4d"
	TEXT_FOREGROUND="#9aa7bd"
elif [[ "$THEME" = "light-blue" ]]; then
	BORDER="0"
	BACKGROUND="#CDEDF6"
	ICON_BACKGROUND="#F5F3F8"
	TEXT_BACKGROUND="#F5F3F8"
	TEXT_FOREGROUND="#0D2C54"
fi

vbar add-css --class switch-theme --css "background-color: $ICON_BACKGROUND"

vbar add-css --class bar --css "font-family: $BASE_FONT;"
vbar add-css --class bar --css "font-weight: normal;"
vbar add-css --class bar --css "font-size: 20px;"
vbar add-css --class bar --css "text-shadow: none;"
vbar add-css --class bar --css "background-color: $BACKGROUND;"
vbar add-css --class bar --css "border: $BORDER solid $BACKGROUND;"

vbar add-css --class block --css "padding-top: 5px;"
vbar add-css --class block --css "padding-bottom: 5px;"
vbar add-css --class block --css "padding-left: 5px;"
vbar add-css --class block --css "padding-right: 5px;"
vbar add-css --class block --css "color: $TEXT_FOREGROUND;"
vbar add-css --class block --css "background-color: $TEXT_BACKGROUND;"

vbar add-css --class menu --css "font-family: $BASE_FONT;"
vbar add-css --class menu --css "font-weight: normal;"
vbar add-css --class menu --css "font-size: 20px;"
vbar add-css --class menu --css "text-shadow: none;"
vbar add-css --class menu --css "background-color: $TEXT_BACKGROUND;"
vbar add-css --class menu --css "color: $TEXT_FOREGROUND;"
vbar add-css --class menu --css "border: 10px solid $TEXT_BACKGROUND;"

vbar add-css --class "menu :hover" --css "background-color: $ICON_BACKGROUND;"
vbar add-css --class "menu :hover" --css "color: $TEXT_FOREGROUND;"

vbar add-css --class desktops --css "letter-spacing: 10px;"
vbar add-css --class desktops --css "background-color: $BACKGROUND;"

vbar add-css --class title --css "background-color: $BACKGROUND;"

vbar add-css --class battery-icon --css "font-family: \"Font Awesome\";"
vbar add-css --class battery-icon --css "font-size: 16px;"
vbar add-css --class battery-icon --css "background-color: $ICON_BACKGROUND;"

vbar add-css --class battery --css "margin-right: 10px;"

vbar add-css --class microphone-icon --css "font-family: \"Font Awesome\";"
vbar add-css --class microphone-icon --css "font-size: 16px;"
vbar add-css --class microphone-icon --css "background-color: $ICON_BACKGROUND;"
vbar add-css --class microphone-icon --css "margin-right: 10px;"

vbar add-css --class volume-icon --css "font-family: \"Font Awesome\";"
vbar add-css --class volume-icon --css "font-size: 16px;"
vbar add-css --class volume-icon --css "background-color: $ICON_BACKGROUND;"

vbar add-css --class volume --css "margin-right: 10px;"

vbar add-css --class wireless-icon --css "font-family: \"Font Awesome\";"
vbar add-css --class wireless-icon --css "font-size: 16px;"
vbar add-css --class wireless-icon --css "background-color: $ICON_BACKGROUND;"

vbar add-css --class wireless --css "margin-right: 10px;"

vbar add-css --class date --css "margin-right: 10px;"

vbar add-css --class time --css "margin-right: 10px;"

vbar add-css --class power-off-icon --css "font-family: \"Font Awesome\";"
vbar add-css --class power-off-icon --css "font-size: 16px;"
vbar add-css --class power-off-icon --css "background-color: $ICON_BACKGROUND;"

vbar add-block --left --name switch-theme --text "" --click-command "switch-theme"

vbar add-block --left --name desktops --command "bspwm-desktops"

vbar add-block --center --name title --tail-command "xtitle -s"

vbar add-block --right --name microphone-icon --command "microphone" --click-command "amixer -q sset Capture toggle && vbar update --name microphone-icon"

vbar add-block --right --name volume-icon --command "volume icon" --click-command "amixer -q sset Master toggle && vbar update --name volume && vbar update --name volume-icon"

vbar add-block --right --name volume --command "volume percentage"

if [[ -d /proc/acpi/battery/BAT* ]]; then
	vbar add-block --right --name battery-icon --text ''
	vbar add-block --right --name battery --tail-command "while true; do acpi | cut -d, -f2 | sed 's/ //'; sleep 5; done"

	vbar add-block --right --name wireless-icon --text ""
	vbar add-block --right --name wireless --command "netctl-auto list | grep '* ' | sed 's/* //'" --interval 5
fi

vbar add-block --right --name date --command "date +%d/%m" --interval 60
vbar add-block --right --name time --command "date +%H:%M" --interval 1

vbar add-block --right --name power-off-icon --text ""
vbar add-menu --name power-off-icon --text "Log off" --command "bspc quit"
vbar add-menu --name power-off-icon --text "Restart" --command "systemctl reboot"
vbar add-menu --name power-off-icon --text "Shut down" --command "systemctl poweroff"
