- pacman:
    name:
      - git
      - git-lfs
      - git-delta
      - tig
      - github-cli

- symlink:
    from: "~/.gitconfig"
    to: ".gitconfig"

- symlink:
    from: "~/.gitignore"
    to: ".gitignore"

- symlink:
    from: "~/.git-template"
    to: ".git-template"
