- pacman:
    name:
      - git
      - git-lfs
      - git-delta
      - difftastic
      - tig

- symlink:
    from: "~/.gitconfig"
    to: ".gitconfig"

- symlink:
    from: "~/.gitignore"
    to: ".gitignore"

- symlink:
    from: "~/.git-template"
    to: ".git-template"
