tasks:
- script:
    command: |
      INCLUDE_LINE='192.168.1.211 homeassistant.local'
      FILE_PATH="/etc/hosts"
      grep -qxF "$INCLUDE_LINE" $FILE_PATH || echo "$INCLUDE_LINE" | sudo tee -a "$FILE_PATH"

- script:
    command: |
      INCLUDE_LINE='192.168.1.176 media.local'
      FILE_PATH="/etc/hosts"
      grep -qxF "$INCLUDE_LINE" $FILE_PATH || echo "$INCLUDE_LINE" | sudo tee -a "$FILE_PATH"

- script:
    command: |
      INCLUDE_LINE='192.168.1.253 mb13.local'
      FILE_PATH="/etc/hosts"
      grep -qxF "$INCLUDE_LINE" $FILE_PATH || echo "$INCLUDE_LINE" | sudo tee -a "$FILE_PATH"

- script:
    command: |
      INCLUDE_LINE='192.168.1.206 desktop.local'
      FILE_PATH="/etc/hosts"
      grep -qxF "$INCLUDE_LINE" $FILE_PATH || echo "$INCLUDE_LINE" | sudo tee -a "$FILE_PATH"
